spring.application.name=salonapi

# H2 localhost in-memory database for development
spring.datasource.url=jdbc:h2:mem:salondb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=test
spring.datasource.password=testtest

# SQL init for local H2 testing
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:H2.migration/schema.sql
spring.sql.init.data-locations=classpath:H2.migration/data.sql

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

springdoc.default-flat-param-object=true

springdoc.swagger-ui.path=/swagger

app.cors.origin=*